### ISSUE TITLE
Connecting Unity Emails to Work on project together

### ISSUE THREAD

**Issue by Kevinthesun456** [CSAllenISD/2023-ISP-TowerDefense#6]
The work on Unity with more members is very tedious and you need to connect other people using their emails. We are not too sure how this would work since we have only had experience using unity just for ourselves and not with others.

**Comment by stefanog1738** [comment]
This is an issue that I experienced when working on my ISP last year. My previous team and I were able to fix this issue but it was a very tedious process. However, I think I am able to remember what we did and how we prevented issues so I am able to help on this matter.

**Comment by SuhraabAlimi** [comment]
We have connected the emails but forgot to close this issue so I am closing it now.
