### ISSUE TITLE
Improving communication and collaboration

### ISSUE THREAD

**Issue by stefanog1738** [CSAllenISD/2023-ISP-TowerDefense#8]
Because members of the team are in different Computer Science Classes, it can get difficult to find a time when we can all be together working on the project or discussing the progress we have made. What we can do is use online platforms to set up meetings, such as Discord.

**Comment by Kevinthesun456** [comment]
Discord is the main use of communication we will be using to interact with our group members since most people have it and is very easy to use. The platform of discord is simple yet complex enough for people to stream each others screen in good quality and usually not have much lag.

**Comment by SuhraabAlimi** [comment]
We have decided to have meetings every Friday on Discord, so communication and collaboration is no longer an issue.
